### ISSUE TITLE
[Request] Config to disable no-fakePlayer-bartering

### ISSUE THREAD

**Issue by Xaikii** [Thelnfamous1/Sapience#1]
I really like the entire concept, and want to include this in my Pack. Yet I also want to be automated Piglin Bartering a thing for the later stages of the game.
`- Piglins will no longer drop barters if the item the bartering item they are admiring did not come from a living being.`
This Feature however no longer makes it possible, having a config option to disable it, would be great.

**Comment by Thelnfamous1** [comment]
Sure, I'll see what I can do.

**Comment by Thelnfamous1** [comment]
Added in latest version.
