### ISSUE TITLE
Piglin barter loop on full inventory

### ISSUE THREAD

**Issue by Spiderach** [Thelnfamous1/Sapience#12]
If one Piglin is traded with frequently enough their inventory will be completely full of gold ingots. When their inventory is full instead of being able to keep the gold ingot they toss it in the air, then are attracted to it and pick it up again. Barter loot drops again, and the loop repeats. Any way to configure things so that if they have a full inventory the gold ingot gets voided?

**Comment by Thelnfamous1** [comment]
That is an oversight that I need to fix, I will make them voided if the inventory is full

**Comment by Thelnfamous1** [comment]
Fixed in latest update for 1.18.2.
