### ISSUE TITLE
Piglin bartering, with tags, doesn't work [1.16.5]

### ISSUE THREAD

**Issue by maxine-red** [Thelnfamous1/Sapience#14]
I'm on 1.16.5 and wanted to add other materials to piglin bartering, but can't get it to work.

I tried to add "data/sapience/tags/items/piglins_barter.json" to my mod pack's data pack and also other variants like, the cheap version, the expensive version and also removing the "s", making it "piglin_barter.json" (and the other variants.

Also added the tags to "piglin_loved", which makes piglins pick up the item and take it, without bartering.

Tags show up in JEI and inventory, so they are assigned, but piglins just don't respond to them. They **do** respond to nuggets and blocks though.
Loot tables work too, it's just the tags that don't work.

EDIT: Also made a barebones try, that only has kubejs (for datapack loading) and sapience
Bartering still only works with gold (tries iron and netherite here)

EDIT 2: OK, did some checking and finally saw this is a 1.18 only feature. Any chances of backporting it to 1.16? If not, feel free to just close this issue

**Comment by Thelnfamous1** [comment]
I won't be backporting features, sorry.
