### ISSUE TITLE
[Request] Piglins will attack someone else at attacks u near of them

### ISSUE THREAD

**Issue by TocinoShimmer** [Thelnfamous1/Sapience#2]
Hello, i recently use this mod at my survival and is pretty nice, i dont have to wear gold armor anymore!

But i have an recomendation:

-Make if the reputation of the piglins is +100 (Maybe 150), they will attack any hostile mob that attacks u, considering that if your reputation is very high, they consider you part of them

Sound pretty good for me.

That's all... :3

Ty for making this awesome mod

![2021-03-27_13 02 45](https://user-images.githubusercontent.com/56833714/112731428-c7356480-8efc-11eb-94e7-f3f9da68625a.png)

**Comment by Thelnfamous1** [comment]
will consider

**Comment by Thelnfamous1** [comment]
This was added since the 1.18.1 version of the mod.

**Comment by TocinoShimmer** [comment]
Really? That sounds awesome! 

I could be great to update it also for the 1.16.5 i mean... For me is the best version for mods without counting the 1.12.2

I'm using it beacuse at the 1.18.1 everything gets too laggy compared with the 1.16.5 or 1.12.2

So, a port for the same version as 1.18.1 for the 1.16.5 could be great, just saying :3
