### ISSUE TITLE
[Suggestion] Piglin Gossip System Extending to Children

### ISSUE THREAD

**Issue by IdrisQe** [Thelnfamous1/Sapience#6]
Looking through the code, from what (admittedly little) I can gleam, the player's reputation can be spread by Piglins "telling" other Piglins where the gold came from when sharing gold, but this only extends to adults, which is a bit of a problem now that baby Piglins can grow up, so if you aren't wearing gold around your 100+ reputation Piglins, the baby could grow up, have 0 reputation since it doesn't have reputation sharing, then attack the player.

It would be nice if there were a way to have the Piglin children perhaps have matching reputation to one of (or a mix of both?) their parents' reputation values until they grow up, at which point it can diverge. Or if that isn't feasible, just let them sort of passively pick up on the "vibes" of other nearby Piglins so it's like they can at least see what's going on around them.

Of course I could be missing something obvious but it seems like it works this way? Been a while since I used the mod so I can't be certain, was thinking of installing it in a current modpack and looking through the features again when this stood out to me.

**Comment by Thelnfamous1** [comment]
I see how that is a problem, I can fix that. Do note that I have moved on to 1.18.1 so any updated mechanics will only be present on that version after I release the initial port.

**Comment by IdrisQe** [comment]
Ah, that's unfortunate but fair. Thanks for the consideration though!

**Comment by Thelnfamous1** [comment]
Baby piglins will now receive gossip from both of their parents when they are born. https://www.curseforge.com/minecraft/mc-mods/sapience/files/3583929
