### ISSUE TITLE
Sapience don't like 1.18.1

### ISSUE THREAD

**Issue by Klouver-github** [Thelnfamous1/Sapience#7]
I feel my heart break when Sapience didn't like 1.18.1 I don't know what to do now and this is the letter he gave me to give to you https://paste.gg/p/anonymous/bd57bf16324549268f1411fec55e4d0e

**Comment by esotericist** [comment]
i get the same final error on 1.18.1 myself.

in case it's useful, i got the following additional data from gdlauncher's stderr logging:
https://gist.github.com/esotericist/f1452fda222194d23c04f4ee5c5555cd

**Comment by SheerAwesomeness** [comment]
+1 - same error for me, even if this is the only mod installed.  Forge 39.0.5

**Comment by ffuentesm** [comment]
I second that, here is my log https://pastebin.com/TzbwXfGx
uring forge 39.0.6

**Comment by Thelnfamous1** [comment]
Crazy crash I didn't catch during testing! Fixing now.

**Comment by Thelnfamous1** [comment]
The new version definitely fixed the issue, check Curseforge, it is uploading as I type this

**Comment by esotericist** [comment]
> The new version definitely fixed the issue, check Curseforge, it is uploading as I type this

thanks so much for getting back to this. i'm really excited to get to try sapience (i'm coming into 1.18 from 1.12, if you can believe it),
