### ISSUE TITLE
Game Crash During Piglin/Wither Skeleton Combat

### ISSUE THREAD

**Issue by Darmandir** [Thelnfamous1/Sapience#9]
Hello, I'm getting a crash when Piglins engage in combat, my testing encompasses Wither Skeletons but this could extend to other mobs.

Forge Version: forge-39.0.8

Steps to reproduce:
1. Create world
2. Enter the Nether
3. Spawn relevant entities (Piglins and a mob they will combat)

[crash-2021-12-22_10.46.32-server.txt](https://github.com/Thelnfamous1/Sapience/files/7764039/crash-2021-12-22_10.46.32-server.txt)

**Comment by Thelnfamous1** [comment]
Sorry about this, I hastily changed something to line up with Mojang's updated code, will be fixed in next release.

**Comment by Thelnfamous1** [comment]
Fixed in latest release: https://www.curseforge.com/minecraft/mc-mods/sapience/files/3583929
